// <auto-generated />
namespace TrainingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Init3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init3));
        
        string IMigrationMetadata.Id
        {
            get { return "202407082352422_Init3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
