// <auto-generated />
namespace TrainingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class init5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init5));
        
        string IMigrationMetadata.Id
        {
            get { return "202407090906500_init5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
